name: Daily Vercel Deployment

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deployment Hook
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: |
          set -euo pipefail
          curl -sS --fail -X POST "$VERCEL_DEPLOY_HOOK"
